apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  aws_access_key_id: QVNJQVVaSFRVWkpQVExFUVNKVzQ=
  aws_secret_access_key: R3hDeVdidnFKMUFibVFyRjcvYksvcjNPNmJVYlIwTjhnL1hOdFA5Mg==