apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: eferoghenej/udagram-api-feed:v1
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports: 
          - containerPort: 8080
        env:
          - name: POSTGRES_HOST
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: POSTGRES_DB
          - name: POSTGRES_USERNAME
            valueFrom: 
              secretKeyRef:
                name: env-secret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: env-secret
                key: POSTGRES_PASSWORD
          - name: AWS_BUCKET
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: AWS_REGION
          - name: AWS_PROFILE
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: AWS_PROFILE
          - name: JWT_SECRET
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: JWT_SECRET
          - name: URL
            valueFrom: 
              configMapKeyRef:
                name: env-configmap
                key: URL
            