apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:    
    matchLabels:      
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: eferoghenej/reverseproxy:v1
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "2048Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always